---
- name: Install and Configure NGINX
  hosts: All
  become: yes
  tasks:

    - name: Update package repositories (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package repositories (RHEL/CentOS/Amazon)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install NGINX on Ubuntu/Debian
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install NGINX on RHEL/CentOS/Amazon
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable NGINX service
      service:
        name: nginx
        state: started
        enabled: yes